### ISSUE TITLE
Release CheckList for 0.7.0

### ISSUE THREAD

**Issue by safaci2000** [esnet/gdg#295]
- [x] Update documentation for wildcard dashboards
- [x] Write blog post for nested folders support
- [x] Update Menu links to point to 0.7.0 release notes by default
- [x] Document api_debug and debug flags
